<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menu')->insert([
            [
                'name' => 'Trang chủ',
                'link' => '/',
                'type' => 'custom',
                'position' => 'mainmenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 1,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Giới thiệu',
                'link' => '/gioi-thieu',
                'type' => 'custom',
                'position' => 'mainmenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 2,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thực đơn',
                'link' => '/thuc-don',
                'type' => 'custom',
                'position' => 'mainmenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 3,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bài viết',
                'link' => '/bai-viet',
                'type' => 'custom',
                'position' => 'mainmenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 4,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hình ảnh',
                'link' => '/hinh-anh',
                'type' => 'custom',
                'position' => 'mainmenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 5,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Liên hệ',
                'link' => '/lien-he',
                'type' => 'custom',
                'position' => 'mainmenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 5,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tin tức',
                'link' => '/tin-tuc',
                'type' => 'custom',
                'position' => 'mainmenu',
                'table_id' => null,
                'parent_id' => 4,
                'sort_order' => 1,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bài viết',
                'link' => '/bai-viet',
                'type' => 'custom',
                'position' => 'mainmenu',
                'table_id' => null,
                'parent_id' => 4,
                'sort_order' => 1,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Điều khoản sử dụng',
                'link' => '/dieu-khoan-du-dung',
                'type' => 'chinh-sach',
                'position' => 'footermenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 1,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chính sách bảo mật',
                'link' => '/chinh-sach-bao-mat',
                'type' => 'chinh-sach',
                'position' => 'footermenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 2,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chính sách vận chuyển',
                'link' => '/chinh-sach-van-chuyen',
                'type' => 'chinh-sach',
                'position' => 'footermenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 3,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chính sách An toàn thực phẩm',
                'link' => '/chinh-sach-an-toan-thuc-pham',
                'type' => 'chinh-sach',
                'position' => 'footermenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 4,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chính sách liên hệ',
                'link' => '/chinh-sach-lien-he',
                'type' => 'chinh-sach',
                'position' => 'footermenu',
                'table_id' => null,
                'parent_id' => 0,
                'sort_order' => 5,
                'created_by' => 1,
                'updated_by' => null,
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
